/*
 * generated by Xtext 2.38.0
 */
package org.xtext.shibainu.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.shibainu.ShibainuRuntimeModule;
import org.xtext.shibainu.ShibainuStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ShibainuIdeSetup extends ShibainuStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ShibainuRuntimeModule(), new ShibainuIdeModule()));
	}
	
}
