/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalShibainuParser;
import org.xtext.example.mydsl.services.ShibainuGrammarAccess;

public class ShibainuParser extends AbstractAntlrParser {

	@Inject
	private ShibainuGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalShibainuParser createParser(XtextTokenStream stream) {
		return new InternalShibainuParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ShibainuGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ShibainuGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
