/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.validation;

import java.util.HashSet;
import java.util.Set;

import org.eclipse.xtext.validation.Check;
import org.xtext.example.mydsl.shibainu.Model;
import org.xtext.example.mydsl.shibainu.Statement;
import org.xtext.example.mydsl.shibainu.VariableDeclaration;
import org.xtext.example.mydsl.shibainu.Conditional;
import org.xtext.example.mydsl.shibainu.Comparison;
import org.xtext.example.mydsl.shibainu.ShibainuPackage;

public class ShibainuValidator extends AbstractShibainuValidator {

    @Check
    public void checkModelo(Model model) {
        Set<String> declaradas = new HashSet<>();

        for (Statement stmt : model.getStatements()) {
            if (stmt instanceof VariableDeclaration decl) {
                String nombre = decl.getName();

                if (declaradas.contains(nombre)) {
                    error("Variable '" + nombre + "' ya fue declarada",
                          decl,
                          ShibainuPackage.Literals.VARIABLE_DECLARATION__NAME);
                } else {
                    declaradas.add(nombre);
                }

            } else if (stmt instanceof Conditional cond) {
                Comparison comp = cond.getComparison();
                String varUsada = comp.getLeft();

                if (!declaradas.contains(varUsada)) {
                    error("La variable '" + varUsada + "' no fue declarada",
                          comp,
                          ShibainuPackage.Literals.COMPARISON__LEFT);
                }
            }
        }
    }
}
