/*
 * generated by Xtext 2.38.0
 */
package org.xtext.shibainu.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractShibainuScopeProvider extends DelegatingScopeProvider {
}
