/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.shibainu.ui.internal.ShibainuActivator;

public class ShibainuUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ShibainuActivator.getInstance().getInjector("org.xtext.example.mydsl.Shibainu");
	}

}
