/**
 * generated by Xtext 2.38.0
 */
package org.xtext.shibainu.shibainu;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparison</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.shibainu.shibainu.Comparison#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.shibainu.shibainu.Comparison#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.shibainu.shibainu.Comparison#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.shibainu.shibainu.ShibainuPackage#getComparison()
 * @model
 * @generated
 */
public interface Comparison extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' attribute.
   * @see #setLeft(String)
   * @see org.xtext.shibainu.shibainu.ShibainuPackage#getComparison_Left()
   * @model
   * @generated
   */
  String getLeft();

  /**
   * Sets the value of the '{@link org.xtext.shibainu.shibainu.Comparison#getLeft <em>Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' attribute.
   * @see #getLeft()
   * @generated
   */
  void setLeft(String value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.shibainu.shibainu.Operator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see org.xtext.shibainu.shibainu.Operator
   * @see #setOperator(Operator)
   * @see org.xtext.shibainu.shibainu.ShibainuPackage#getComparison_Operator()
   * @model
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link org.xtext.shibainu.shibainu.Comparison#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see org.xtext.shibainu.shibainu.Operator
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' attribute.
   * @see #setRight(int)
   * @see org.xtext.shibainu.shibainu.ShibainuPackage#getComparison_Right()
   * @model
   * @generated
   */
  int getRight();

  /**
   * Sets the value of the '{@link org.xtext.shibainu.shibainu.Comparison#getRight <em>Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' attribute.
   * @see #getRight()
   * @generated
   */
  void setRight(int value);

} // Comparison
