/**
 * generated by Xtext 2.38.0
 */
package org.xtext.shibainu.shibainu;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.shibainu.shibainu.Conditional#getComparison <em>Comparison</em>}</li>
 *   <li>{@link org.xtext.shibainu.shibainu.Conditional#getStatement <em>Statement</em>}</li>
 * </ul>
 *
 * @see org.xtext.shibainu.shibainu.ShibainuPackage#getConditional()
 * @model
 * @generated
 */
public interface Conditional extends Statement
{
  /**
   * Returns the value of the '<em><b>Comparison</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparison</em>' containment reference.
   * @see #setComparison(Comparison)
   * @see org.xtext.shibainu.shibainu.ShibainuPackage#getConditional_Comparison()
   * @model containment="true"
   * @generated
   */
  Comparison getComparison();

  /**
   * Sets the value of the '{@link org.xtext.shibainu.shibainu.Conditional#getComparison <em>Comparison</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparison</em>' containment reference.
   * @see #getComparison()
   * @generated
   */
  void setComparison(Comparison value);

  /**
   * Returns the value of the '<em><b>Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' containment reference.
   * @see #setStatement(Statement)
   * @see org.xtext.shibainu.shibainu.ShibainuPackage#getConditional_Statement()
   * @model containment="true"
   * @generated
   */
  Statement getStatement();

  /**
   * Sets the value of the '{@link org.xtext.shibainu.shibainu.Conditional#getStatement <em>Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement</em>' containment reference.
   * @see #getStatement()
   * @generated
   */
  void setStatement(Statement value);

} // Conditional
