/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.shibainu;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.shibainu.Print#getMessage <em>Message</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.shibainu.ShibainuPackage#getPrint()
 * @model
 * @generated
 */
public interface Print extends Statement
{
  /**
   * Returns the value of the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' attribute.
   * @see #setMessage(String)
   * @see org.xtext.example.mydsl.shibainu.ShibainuPackage#getPrint_Message()
   * @model
   * @generated
   */
  String getMessage();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.shibainu.Print#getMessage <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' attribute.
   * @see #getMessage()
   * @generated
   */
  void setMessage(String value);

} // Print
