/*
 * generated by Xtext 2.38.0
 */
package org.xtext.shibainu.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ShibainuUiModule extends AbstractShibainuUiModule {

	public ShibainuUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
