/*
 * generated by Xtext 2.38.0
 */
package org.xtext.shibainu.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ShibainuAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/shibainu/parser/antlr/internal/InternalShibainu.tokens");
	}
}
