/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.shibainu.ui.internal.ShibainuActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ShibainuExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ShibainuActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ShibainuActivator activator = ShibainuActivator.getInstance();
		return activator != null ? activator.getInjector(ShibainuActivator.ORG_XTEXT_EXAMPLE_MYDSL_SHIBAINU) : null;
	}

}
